"""initial schema (full data model)

Revision ID: fa4559003e71
Revises:
Create Date: 2026-07-14 18:12:31.188708

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa4559003e71"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "judge_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prompt_template", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Integer(), nullable=False),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('builtin', 'custom')", name="ck_templates_kind"),
        sa.CheckConstraint("version >= 1", name="ck_templates_version_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_templates_name_version"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("api_key_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('admin', 'reviewer', 'annotator')", name="ck_users_role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_api_key_hash"), "users", ["api_key_hash"], unique=False)
    op.create_table(
        "annotators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("judge_config_id", sa.Integer(), nullable=True),
        sa.Column("reputation_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'human' AND user_id IS NOT NULL) OR (kind = 'model' AND judge_config_id IS NOT NULL)",
            name="ck_annotators_kind_links",
        ),
        sa.CheckConstraint("kind IN ('human', 'model')", name="ck_annotators_kind"),
        sa.ForeignKeyConstraint(["judge_config_id"], ["judge_configs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("template_version", sa.Integer(), nullable=False),
        sa.Column("guidelines_md", sa.Text(), nullable=True),
        sa.Column("labels_per_unit", sa.Integer(), nullable=False),
        sa.Column("max_labels_per_unit", sa.Integer(), nullable=False),
        sa.Column("agreement", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("gold_ratio", sa.Float(), nullable=False),
        sa.Column("lease_minutes", sa.Integer(), nullable=False),
        sa.Column("min_reputation", sa.Float(), nullable=False),
        sa.Column("pipeline", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "gold_ratio >= 0 AND gold_ratio <= 1", name="ck_projects_gold_ratio_range"
        ),
        sa.CheckConstraint("labels_per_unit >= 1", name="ck_projects_labels_per_unit_positive"),
        sa.CheckConstraint(
            "max_labels_per_unit >= labels_per_unit", name="ck_projects_max_labels_ge_labels"
        ),
        sa.ForeignKeyConstraint(["template_id"], ["templates.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("source_filename", sa.String(length=500), nullable=True),
        sa.Column("unit_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_batches_project_id"), "batches", ["project_id"], unique=False)
    op.create_table(
        "reputation_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("annotator_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("delta", sa.Float(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('gold_pass', 'gold_fail', 'agreement', 'bias_flag', 'speed_flag')",
            name="ck_reputation_events_kind",
        ),
        sa.ForeignKeyConstraint(["annotator_id"], ["annotators.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reputation_events_annotator_id"),
        "reputation_events",
        ["annotator_id"],
        unique=False,
    )
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event", sa.String(length=50), nullable=False),
        sa.Column("target_url", sa.String(length=1000), nullable=False),
        sa.Column("secret", sa.String(length=200), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event IN ('budget.cap_reached', 'gold.accuracy_dropped', 'review.queue_backlog', 'project.completed')",
            name="ck_webhooks_event",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhooks_project_id"), "webhooks", ["project_id"], unique=False)
    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_gold", sa.Boolean(), nullable=False),
        sa.Column("gold_expected", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'in_progress', 'labeled', 'finalized')", name="ck_units_status"
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_units_batch_id"), "units", ["batch_id"], unique=False)
    op.create_index(op.f("ix_units_project_id"), "units", ["project_id"], unique=False)
    op.create_table(
        "final_labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("decided_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('auto_consensus', 'human_approved', 'human_override', 'expert')",
            name="ck_final_labels_method",
        ),
        sa.ForeignKeyConstraint(["decided_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_final_labels_unit_id"), "final_labels", ["unit_id"], unique=False)
    op.create_table(
        "slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("variant", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("leased_by", sa.Integer(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'leased', 'filled', 'voided')", name="ck_slots_status"
        ),
        sa.ForeignKeyConstraint(["leased_by"], ["annotators.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_slots_unit_id"), "slots", ["unit_id"], unique=False)
    op.create_table(
        "labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slot_id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("annotator_id", sa.Integer(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["annotator_id"], ["annotators.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["slot_id"], ["slots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_labels_annotator_id"), "labels", ["annotator_id"], unique=False)
    op.create_index(op.f("ix_labels_slot_id"), "labels", ["slot_id"], unique=False)
    op.create_index(op.f("ix_labels_unit_id"), "labels", ["unit_id"], unique=False)
    op.create_index(
        "uq_labels_annotator_unit_valid",
        "labels",
        ["annotator_id", "unit_id"],
        unique=True,
        postgresql_where="is_valid",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_labels_annotator_unit_valid", table_name="labels", postgresql_where="is_valid"
    )
    op.drop_index(op.f("ix_labels_unit_id"), table_name="labels")
    op.drop_index(op.f("ix_labels_slot_id"), table_name="labels")
    op.drop_index(op.f("ix_labels_annotator_id"), table_name="labels")
    op.drop_table("labels")
    op.drop_index(op.f("ix_slots_unit_id"), table_name="slots")
    op.drop_table("slots")
    op.drop_index(op.f("ix_final_labels_unit_id"), table_name="final_labels")
    op.drop_table("final_labels")
    op.drop_index(op.f("ix_units_project_id"), table_name="units")
    op.drop_index(op.f("ix_units_batch_id"), table_name="units")
    op.drop_table("units")
    op.drop_index(op.f("ix_webhooks_project_id"), table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_index(op.f("ix_reputation_events_annotator_id"), table_name="reputation_events")
    op.drop_table("reputation_events")
    op.drop_index(op.f("ix_batches_project_id"), table_name="batches")
    op.drop_table("batches")
    op.drop_table("projects")
    op.drop_table("annotators")
    op.drop_index(op.f("ix_users_api_key_hash"), table_name="users")
    op.drop_table("users")
    op.drop_table("templates")
    op.drop_table("judge_configs")
    # ### end Alembic commands ###
